// Generates the prediction-data pack the Node build reads at runtime.
//
// Emits two files under src/generated/ (git-ignored, regenerated on build/test):
//   stations.pack   concatenated UTF-8 JSON records {harmonic_constituents, datums, epoch}
//   pack-index.ts   id -> [byteOffset, byteLength] into the pack
//
// The pack ships as a package asset and is loaded into an off-heap Buffer, so
// importing tide-database no longer holds every station's prediction data on the
// V8 heap. Offsets are UTF-8 byte offsets (station names carry multibyte chars).

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = join(root, "data");
const outDir = join(root, "src", "generated");

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = join(dir, e.name);
    return e.isDirectory() ? walk(p) : p.endsWith(".json") ? [p] : [];
  });
}

// Sorted for a deterministic pack layout.
const files = walk(dataDir).sort();

const chunks = [];
const index = {};
const references = [];
let offset = 0;

for (const file of files) {
  const id = file.slice(dataDir.length + 1).replace(/\.json$/, "");
  const s = JSON.parse(readFileSync(file, "utf8"));
  if (s.type === "subordinate" && s.offsets?.reference) {
    references.push([id, s.offsets.reference]);
  }
  const record = JSON.stringify({
    harmonic_constituents: s.harmonic_constituents ?? [],
    datums: s.datums ?? {},
    epoch: s.epoch,
  });
  const buf = Buffer.from(record, "utf8");
  index[id] = [offset, buf.length];
  chunks.push(buf);
  offset += buf.length;
}

// Fail the build if any subordinate points at a missing reference — otherwise it
// would only surface at prediction time as a runtime error.
for (const [id, reference] of references) {
  if (!(reference in index)) {
    throw new Error(
      `Station ${id} references missing reference station ${reference}`,
    );
  }
}

const pack = Buffer.concat(chunks);

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "stations.pack"), pack);
writeFileSync(
  join(outDir, "pack-index.ts"),
  "// Generated by scripts/generate-pack.mjs — do not edit.\n" +
    "export const packIndex: Record<string, [number, number]> = " +
    JSON.stringify(index) +
    ";\n",
);

console.log(
  `generated pack: ${(pack.length / 1048576).toFixed(1)} MB, ${files.length} stations, ` +
    `index ${(Buffer.byteLength(JSON.stringify(index)) / 1048576).toFixed(2)} MB`,
);
